version: "3.8"

services:
  geth:
    image: '${GETH_IMAGE}'
    pull_policy: always
    container_name: geth
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    healthcheck:
      test: [ "CMD-SHELL", "geth --datadir=/data attach  --exec eth.blockNumber" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - ${GETH_P2P_PORT}:${GETH_P2P_PORT}
    - ${GETH_P2P_PORT}:${GETH_P2P_PORT}/udp
    - 8545:8545
    - 8546:8546
    - 8551:8551
    volumes:
    - /data/geth:/data
    command:
    - --datadir=/data
    - --http
    - --http.addr=0.0.0.0
    - --http.api=eth,net,web3,engine,admin
    - --http.vhosts=*
    - --http.corsdomain=*
    - --ws
    - --ws.origins=*
    - --ws.addr=0.0.0.0
    - --ws.api=eth,net,web3
    - --graphql
    - --graphql.corsdomain=*
    - --graphql.vhosts=*
    - --authrpc.addr=0.0.0.0
    - --authrpc.vhosts=*
    - --authrpc.jwtsecret=/data/jwt.hex
    - --authrpc.port=8551
    - --txlookuplimit=0
    - --nat=extip:${PUBLIC_IP}
    - --port=${GETH_P2P_PORT}
    - --maxpeers=300
    - --${NETWORK}
    - --syncmode=snap
    - --db.engine=leveldb
    - --metrics
    - --pprof
    - --pprof.addr=0.0.0.0
    - --pprof.port=6060
  prysm:
    image: '${PRYSM_IMAGE}'
    pull_policy: always
    container_name: prysm
    restart: unless-stopped
    stop_grace_period: 2m
    volumes:
    - /data/prysm:/data
    - /data/geth:/geth
    depends_on:
      geth:
        condition: service_healthy
    ports:
    - 8080:8080
    - ${PRYSM_P2P_PORT}:${PRYSM_P2P_PORT}
    - ${PRYSM_P2P_PORT}:${PRYSM_P2P_PORT}/udp
    command:
    - --datadir=/data
    - --rpc-host=0.0.0.0
    - --rpc-port=4000
    - --accept-terms-of-use
    - --execution-endpoint=http://geth:8551
    - --jwt-secret=/geth/jwt.hex
    - --enable-debug-rpc-endpoints
    - --${NETWORK}
    - --accept-terms-of-use
    - --p2p-max-peers=160
    - --enable-debug-rpc-endpoints
    - --checkpoint-sync-url=${CHECKPOINT_URL}
    - --subscribe-all-subnets
    - --monitoring-port=9090
    - --monitoring-host=0.0.0.0
    - --http-mev-relay=http://mev-boost:18550
    - --grpc-gateway-host=0.0.0.0
    - --grpc-gateway-port=8080
    - --p2p-host-ip=${PUBLIC_IP}
    - --p2p-tcp-port=${PRYSM_P2P_PORT}
    - --p2p-udp-port=${PRYSM_P2P_PORT}
  mev-boost: 
    image: ${MEV_IMAGE}
    pull_policy: always
    container_name: mev-boost
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m 
    ports: 
    - 18550:18550
    command: 
    - -${NETWORK}
    - -relays
    - ${MEV_RELAYS}
    - -addr 
    - 0.0.0.0:18550
